### PR TITLE
dorado_trimming feedback from testing

### PR DESCRIPTION
**Pull request by TomHarrop**
@AnnaSyme I'm tracking changes for the dorado read trimmer here, let me know if there's anything else!
- [x] Don't allow custom primers with `--no-trim-primers`

### CODE REVIEW

**Comment by AnnaSyme** [comment]
thanks @TomHarrop !

**Comment by AnnaSyme** [comment]
@TomHarrop to convert the output bam file of trimmed reads to fastq, I'm using "samtoFastq", but it's giving me an error. 
history: https://dev.gvl.org.au/u/annasyme/h/dorado
not sure if this is something to do with the dorado output itself, or something else.

**Comment by TomHarrop** [comment]
@AnnaSyme I've used [Samtools fastx](https://usegalaxy.org.au/root?tool_id=toolshed.g2.bx.psu.edu/repos/iuc/samtools_fastx/samtools_fastx/1.15.1+galaxy2) to get the reads out of the basecalling files. I think it should work for the trimming output too.

**Comment by AnnaSyme** [comment]
@TomHarrop that looks good, yes. I'll try out fastp perhaps on the reads before and after trimming to see if we can get any info about what was trimmed. (unless another tool seems better for that?)

**Pull request merged**
