### PR TITLE
Use a data table for alphafold reference data

### PR DESCRIPTION
**Pull request by bernt-matthias**
because an environment variable does not work on instances that do not use TPV. this is because  version specific destinations can not be configured (i.e. version specific environment variables are impossible)

for admins the change is to add an entry to the data table for each version

users will see another parameter that they can't change. so there is no room for user error.

I tested this on my test instance (jobs are running successfully since 1h).

### CODE REVIEW

**Comment by cat-bro** [comment]
@bernt-matthias where is your alphafold reference data relative to your Galaxy server? Are you using pulsar?

**Comment by bernt-matthias** [comment]
We have two folders

```
/data/db/alphafold/2.1.2/2022-11-14/
/data/db/alphafold/2.3.1/2023-03-21/
```

I'm not using pulsar.

**Comment by bernt-matthias** [comment]
If you want to avoid the extra parameter + data table we could define that `$ALPHAFOLD_DB` should point to a directory that contains subdirectories that are named like the AF versions. That is the version specific data would be in:

`\${ALPHAFOLD_DB:-/data}/@TOOL_VERSION@/`

Should also work for me .. I would need to place some symlinks in a helper directory...

For me I would create a directory `/GALAXY_ROOT/tool-data/alphafold_db/`

```
/GALAXY_ROOT/tool-data/alphafold_db/2.1.2 -> /data/db/alphafold/2.1.2/2022-11-14/
/GALAXY_ROOT/tool-data/alphafold_db/2.3.1 -> /data/db/alphafold/2.3.1/2023-03-21/
```

**Comment by bernt-matthias** [comment]
Instead of the default `/data` we could also use something like `$__tool_data_path__/alphafold_reference/`

**Comment by neoformit** [comment]
@bernt-matthias Yes the data table solution apparently gets tricky on Pulsar. I think the hard-coded subdir is a good solution. What would `$__tool_data_path__` resolve to? I assume this path would not exist by default in the docker container? Or is there a default bind path for this?

**Comment by bernt-matthias** [comment]
`$__tool_data_path__` is Galaxy's `tool-data` folder.

**Pull request merged**
