### PR TITLE
use a config file to pass input to lfq-analyst

### PR DESCRIPTION
**Pull request by TomHarrop**
Just using this branch to track my attempts to get lfqanalyst running inside Galaxy, because I'll need this info for TMT analyst.

### CODE REVIEW

**Comment by TomHarrop** [comment]
I'm able to pass the port in and get to the LFQ analyst interface, but I can't work out how to open it from Galaxy. Clicking the "eye" icon opens a blank page.

**Comment by neoformit** [comment]
> 

This probably means the tool isn't working - UI feedback for ITs is very poor in v22.05. Has been improved in latest release I think. You can find "Active interactive tools" page under `User` menu.

**Comment by TomHarrop** [comment]
I have the link showing on dev but I'm getting `Proxy target missing` when I click on it. There's an error in galaxy-gie-proxy:

```bash
$ sudo journalctl -fu galaxy-gie-proxy
May 24 04:15:32 dev node[2713898]: Proxy error:  { Error: connect ECONNREFUSED 45.113.233.251:49194
May 24 04:15:32 dev node[2713898]:     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)
May 24 04:15:32 dev node[2713898]:   errno: 'ECONNREFUSED',
May 24 04:15:32 dev node[2713898]:   code: 'ECONNREFUSED',
May 24 04:15:32 dev node[2713898]:   syscall: 'connect',
May 24 04:15:32 dev node[2713898]:   address: '45.113.233.251',
May 24 04:15:32 dev node[2713898]:   port: 49194 }
```

Just posting it here FTR.

**Comment by TomHarrop** [comment]
Networking issue was fixed in https://github.com/usegalaxy-au/tools-au/pull/80/commits/6074b5996b2f8c25a7c0a2730d3a2be3e25a823d by telling Shiny to listen on `0.0.0.0`.

We should definitely document this :upside_down_face:

**Pull request merged**
